# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='user',
            new_name='driver_user',
        ),
        migrations.AlterField(
            model_name='driver',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.Car'),
        ),
    ]
