# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_auto_20180519_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup_location',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='driver',
            name='passenger_pickup',
        ),
        migrations.AddField(
            model_name='driver',
            name='passenger_pickup',
            field=models.ManyToManyField(to='driver.Pickup_Location'),
        ),
    ]
