# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_auto_20180523_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickup_location',
            old_name='location',
            new_name='geom',
        ),
    ]
