# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0008_auto_20180524_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='passenger_pickup',
            field=models.ManyToManyField(null=True, to='driver.Pickup_Location'),
        ),
    ]
