# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0009_auto_20180524_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='driver_image',
        ),
        migrations.AddField(
            model_name='car',
            name='car_photo',
            field=models.ImageField(blank=True, upload_to='driver/static/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='passenger_pickup',
            field=models.ManyToManyField(to='driver.Pickup_Location'),
        ),
    ]
