# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0010_auto_20180524_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='name',
            new_name='place',
        ),
    ]
