# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 08:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver', '0012_car_car_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='driver_place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
