# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 15:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0016_auto_20180526_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='pickups',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pickups', to='driver.Pickup_Location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='driver_place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
