# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 13:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver', '0017_auto_20180526_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup_location',
            name='pointer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
