# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0018_pickup_location_pointer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='pickups',
        ),
        migrations.AddField(
            model_name='destination',
            name='pickups',
            field=models.ManyToManyField(to='driver.Pickup_Location'),
        ),
    ]
