# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 12:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=60)),
                ('phone', models.IntegerField()),
                ('final_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.Destination')),
                ('pickup_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.Pickup_Location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
