# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='final_destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.Destination'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='pickup_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.Pickup_Location'),
        ),
    ]
