# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0003_passenger_driver_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='driver_image',
            new_name='rider_image',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='user',
            new_name='rider_user',
        ),
    ]
