# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0004_auto_20180528_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
