# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 12:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0005_auto_20180528_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='rider_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
